function options = training_options(optimizer,Initial_rate,DropFactor,DropPeriod,MaxEpochs,MiniBatchSize,validate)
%Dina Abdelhafiz
%summary:traning options for deep learning models
%optimizer='ada' or 'sgdm'
if (optimizer=='adam')
    options = trainingOptions('adam', ...
        'InitialLearnRate',Initial_rate, ...
        'LearnRateSchedule','piecewise',...
        'LearnRateDropFactor',DropFactor,...
        'LearnRateDropPeriod',DropPeriod,...
        'MaxEpochs',MaxEpochs,...
        'Shuffle','every-epoch',...
        'MiniBatchSize',MiniBatchSize,...
        'Verbose',true,...
        'GradientDecayFactor',0.9,...
        'SquaredGradientDecayFactor',0.999,...
        'Epsilon',0.1,...
        'GradientThresholdMethod','l2norm',...
        'GradientThreshold',0.05,...
        'L2Regularization',0.0005,...
        'ExecutionEnvironment','gpu',...
        'WorkerLoad',36,...
        'Plots','training-progress',...
        'ValidationData',validate,...
        'ValidationFrequency',10,...
        'ValidationPatience',Inf);
elseif (optimizer=='sgdm')
    options = trainingOptions('sgdm',...
        'InitialLearnRate',Initial_rate,...
        'LearnRateSchedule','piecewise',...
        'LearnRateDropFactor',DropFactor,...
        'LearnRateDropPeriod',DropPeriod,...
        'Momentum',0.9,...
        'MaxEpochs',MaxEpochs,...
        'Shuffle','every-epoch',...
        'MiniBatchSize',MiniBatchSize,...
        'Verbose',true,...
        'L2Regularization',0.005,...
        'GradientThresholdMethod','l2norm',...
        'GradientThreshold',0.05,...
        'ExecutionEnvironment','gpu',...
        'WorkerLoad',36,...
        'Plots','training-progress',...
        'ValidationData',validate,...
        'ValidationFrequency',50,...
        'ValidationPatience',Inf);
end
end